Release lock on exception in sensor callback
If ROS bridge gets terminated (for example using ctrl-c) while it's
processing a sensor callback, `_callback_active` lock wouldn't get
released, causing `CarlaRosBridge::destroy` later to stall when destroying
the sensor and to not destroy some actors.

Here is the exception that happened in sensor callback:

```
Traceback (most recent call last):
  File ".../carla_ros_bridge/sensor.py", line 183, in _callback_sensor_data
Traceback (most recent call last):
  File ".../carla_ros_bridge/sensor.py", line 183, in _callback_sensor_data
    self.publish_tf(trans.carla_transform_to_ros_pose(
  File ".../carla_ros_bridge/sensor.py", line 144, in publish_tf
    self._tf_broadcaster.sendTransform(transform)
    self.publish_tf(trans.carla_transform_to_ros_pose(
  File ".../carla_ros_bridge/sensor.py", line 144, in publish_tf
  File ".../site-packages/tf2_ros/transform_broadcaster.py", line 77, in sendTransform
    self.pub_tf.publish(TFMessage(transforms=transform))
  File ".../site-packages/rclpy/publisher.py", line 70, in publish
    self._tf_broadcaster.sendTransform(transform)
  File ".../site-packages/tf2_ros/transform_broadcaster.py", line 77, in sendTransform
    self.pub_tf.publish(TFMessage(transforms=transform))
  File ".../site-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at /build/rcl-release-release-jazzy-rcl-9.2.4-1/src/rcl/publisher.c:423
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at /build/rcl-release-release-jazzy-rcl-9.2.4-1/src/rcl/publisher.c:423
```